{% set versions = {
    "v3r72": "594d1f0883533a4404e6e45acf01a86e93afa86a6d0110b8697732163c7a8641"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "framel")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://git.ligo.org/virgo/virgoapp/Fr/-/archive/{{  version }}/Fr-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

    - make
    - cmake

about:
  home: "https://git.ligo.org/virgo/virgoapp/Fr"
  license: "GPL-3.0"
  summary: "Frame library"
  description: |
    Frame library

extra:
  recipe-maintainers:
    - meiyasan
