{% set versions = {
    "8.48.4": "0607181a5494ec4962b0ed8f8901e02fce85598274740730fef9889ae989f908"
} %}


{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "framel")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: "https://git.ligo.org/virgo/virgoapp/Fr/-/archive/{{  version }}/Fr-{{ version }}.tar.gz"
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}

patches:
    - patches/stdlib.patch

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - python

    - make
    - cmake

  host:
    - python

  run:
    - python

about:
  home: "https://git.ligo.org/virgo/virgoapp/Fr"
  license: "GPL-3.0"
  summary: "Frame library"
  description: |
    Frame library

extra:
  recipe-maintainers:
    - meiyasan
